name: Sercan ERHAN
description: 
meta_description: "Sercan ERHAN"

markdown: redcarpet
pygments: true

baseurl: 

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'sercanerhan.github.io'
author:         'Sercan ERHAN'


